name: Build Kernel Headers for Armbian from ophub/amlogic-s9xxx-armbian

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev libelf-dev wget git
      
    - name: Clone ophub/amlogic-s9xxx-armbian Repository
      run: |
        git clone https://github.com/ophub/amlogic-s9xxx-armbian.git
        
    - name: Switch to Specific Tag and Prepare Kernel Source
      working-directory: amlogic-s9xxx-armbian
      run: |
        git fetch --tags
        git checkout Armbian_noble_save_2025.04  # 使用正确的标签名
        
    - name: Download Kernel Source
      run: |
        mkdir -p amlogic-s9xxx-armbian/kernel
        wget https://github.com/ophub/kernel/releases/download/kernel_rk35xx/6.1.99.tar.gz -P amlogic-s9xxx-armbian/kernel/
        
    - name: Extract Kernel Source
      working-directory: amlogic-s9xxx-armbian/kernel
      run: tar -xvf 6.1.99.tar.gz
      
    - name: Create Target Directory for Headers
      run: mkdir -p ./kernel_headers
      
    - name: Extract Header Files
      working-directory: amlogic-s9xxx-armbian/kernel/6.1.99
      run: tar -xvf header-6.1.99-rk35xx-ophub.tar.gz -C ../../kernel_headers
      
    - name: Verify Header Files Exist
      run: |
        if [ -d "./kernel_headers/include" ] && [ -d "./kernel_headers/arch" ] && [ -f "./kernel_headers/Module.symvers" ]; then 
          echo "Headers found"
        else 
          echo "Headers not found"
        fi

    - name: Archive Kernel Headers
      run: |
        tar -czf kernel-headers.tar.gz -C ./kernel_headers .

    - name: Upload Kernel Headers Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: kernel-headers
        path: amlogic-s9xxx-armbian/kernel-headers.tar.gz
