name: Build Kernel Headers for Armbian from ophub/amlogic-s9xxx-armbian

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev libelf-dev wget git
      
    - name: Clone ophub/amlogic-s9xxx-armbian Repository
      run: |
        git clone https://github.com/ophub/amlogic-s9xxx-armbian.git
        
    - name: Switch to Specific Tag and Prepare Kernel Source
      working-directory: amlogic-s9xxx-armbian
      run: |
        # 获取所有标签
        git fetch --tags
        # 切换到包含所需内核版本的标签
        git checkout Armbian_noble_save_2025.04  # 使用正确的标签名
        
    - name: Download Kernel Source
      run: |
        mkdir -p kernel
        wget https://github.com/ophub/kernel/releases/download/kernel_rk35xx/6.1.99.tar.gz -P kernel/
        
    - name: Extract Kernel Source
      working-directory: amlogic-s9xxx-armbian/kernel
      run: tar -xvf 6.1.99.tar.gz
      
    - name: Copy Configuration File and Compile Kernel Headers
      working-directory: amlogic-s9xxx-armbian
      run: |
        # 复制配置文件到内核源码目录
        cp compile-kernel/tools/config/config-6.1 kernel/.config
        cd kernel
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- prepare
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- headers_check
        sudo make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- INSTALL_HDR_PATH=/usr/local headers_install
        
    - name: Archive Kernel Headers
      run: |
        tar -czf kernel-headers.tar.gz -C /usr/local/include .

    - name: Verify artifact exists
      run: if [ -f "amlogic-s9xxx-armbian/kernel-headers.tar.gz" ]; then echo "Artifact found"; else echo "Artifact not found"; fi

    - name: Upload Kernel Headers Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: kernel-headers
        path: amlogic-s9xxx-armbian/kernel-headers.tar.gz  # 确认路径是否正确
