name: Build Kernel Headers for Armbian from ophub/amlogic-s9xxx-armbian

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev libelf-dev wget git
      
    - name: Clone ophub/amlogic-s9xxx-armbian Repository
      run: |
        git clone https://github.com/ophub/amlogic-s9xxx-armbian.git
        
    - name: Switch to Specific Tag and Prepare Kernel Source
      working-directory: amlogic-s9xxx-armbian
      run: |
        # 切换到包含所需内核版本的标签
        git fetch --tags
        git checkout Armbian_noble_save_2025.04  # 替换成实际找到的标签名
        cd compile-kernel/tools/config
        # 假设配置文件位于compile-kernel/tools/config下
        cp config-6.1 ../../../kernel/.config
        cd ../../../kernel
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- prepare
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- headers_check
        sudo make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- INSTALL_HDR_PATH=/usr/local headers_install
        
    - name: Archive Kernel Headers
      run: |
        tar -czf kernel-headers.tar.gz -C /usr/local/include .
      uses: actions/upload-artifact@v2
      with:
        name: kernel-headers
        path: kernel-headers.tar.gz
